-- -----------------------------------------------------
-- Table `FRIENDSHIP`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PLACE` ;
DROP TABLE IF EXISTS `PLACE_CATEGORY` ;
DROP TABLE IF EXISTS `PERSON_FRIENDSHIP` ;
-- Friendship table removed from schema
DROP TABLE IF EXISTS `FRIENDSHIP` ;
DROP TABLE IF EXISTS `USER` ;

-- -----------------------------------------------------
-- Table USER`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `USER` (
  `USER_ID` INT NOT NULL AUTO_INCREMENT,
  `EMAIL` VARCHAR(255) NOT NULL,
  `FIRSTNAME` VARCHAR(50) NOT NULL,
  `LASTNAME` VARCHAR(50) NOT NULL,
  `PASSWORD` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`USER_ID`),
  UNIQUE INDEX `EMAIL_UNIQUE` (`EMAIL` ASC));

-- -----------------------------------------------------
-- Table `PERSON_FRIENDSHIP`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `PERSON_FRIENDSHIP` (
  `PERSON_FRIENDSHIP_ID` INT NOT NULL AUTO_INCREMENT,
  `USER_ID` INT NOT NULL,
  `FRIEND_ID` INT NOT NULL,
  PRIMARY KEY (`PERSON_FRIENDSHIP_ID`),
  FOREIGN KEY (`USER_ID`) REFERENCES USER(`USER_ID`),
  FOREIGN KEY (`FRIEND_ID`) REFERENCES USER(`USER_ID`));

-- -----------------------------------------------------
-- Table `PLACE_CATEGORY`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `PLACE_CATEGORY` (
  `CATEGORY_ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`CATEGORY_ID`));
-- -----------------------------------------------------
-- Table `PLACE`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `PLACE` (
  `PLACE_ID` INT NOT NULL AUTO_INCREMENT,
  `CATEGORY_ID` INT NOT NULL,
  `NAME` VARCHAR(255) NOT NULL,
  `DESCRIPTION` VARCHAR(4095) NOT NULL,
  `LATITUDE` VARCHAR(4095) NULL DEFAULT NULL,
  `LONGITUDE` VARCHAR(4095) NULL DEFAULT NULL,
  `ADDRESS` VARCHAR(4095) NULL DEFAULT NULL,
  `EMAIL` VARCHAR(255) NULL DEFAULT NULL,
  `PHONE` VARCHAR(12) NULL DEFAULT NULL,
  `ADDED_BY_USER_ID` INT NOT NULL,

  PRIMARY KEY (`PLACE_ID`),
  INDEX `IDX_PLA_CAT` (`CATEGORY_ID` ASC),
  FOREIGN KEY (`CATEGORY_ID`) REFERENCES `PLACE_CATEGORY` (`CATEGORY_ID`),
  FOREIGN KEY (`ADDED_BY_USER_ID`) REFERENCES `USER`(`USER_ID`));
