//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pietryna.API.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ddEntities : DbContext
    {
        public ddEntities()
            : base("name=ddEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<person_friendship> person_friendship { get; set; }
        public virtual DbSet<place> places { get; set; }
        public virtual DbSet<place_category> place_category { get; set; }
        public virtual DbSet<rate> rates { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
