//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pietryna.API.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class person_friendship
    {
        public int PERSON_FRIENDSHIP_ID { get; set; }
        public int USER_ID { get; set; }
        public int FRIEND_ID { get; set; }
    
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
    }
}
