//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pietryna.API.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class place
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public place()
        {
            this.rates = new HashSet<rate>();
        }
    
        public int PLACE_ID { get; set; }
        public int CATEGORY_ID { get; set; }
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public string LATITUDE { get; set; }
        public string LONGITUDE { get; set; }
        public string ADDRESS { get; set; }
        public string EMAIL { get; set; }
        public string PHONE { get; set; }
        public int ADDED_BY_USER_ID { get; set; }
    
        public virtual place_category place_category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rate> rates { get; set; }
        public virtual user user { get; set; }
    }
}
